name: Docker series build
on: push

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker  build /.github/workflows -t ganeshkrish/maven-web-application:1 .
 




