name: Docker series build
on: push

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker  build /GaneshKrishna112/docker container/docker-sample -t ganeshkrish/docker-samplemaven-web-application:1
 




