name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-actions@v1
      with:
        username: ${{ ganeskrish }}
        password: ${{ 1e6c6e12-fabd-4c80-bee3-3e67def54560 }}
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        uses: actions/checkout@v3
    - name: Build the Docker image
        run:docker build . --docker-container --tag maven-web-application:$(1)
      
